config/routes.rb
Rails.application.routes.draw do
  resources :upload_pictures do
    collection do
      get 'main'
    end
  end

  root :to => 'upload_pictures#main'

end

app/models/upload_picture.rb
class UploadPicture < ActiveRecord::Base
  
  has_attached_file :image, :path => ":rails_root/public/system/images/:filename", :url => "/system/images/:filename"
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/jpe', 'image/jpg', 'image/pjpeg']
  validates_attachment_presence :image
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/upload_pictures_controller.rb
class UploadPicturesController < ApplicationController
  before_action :set_upload_picture, only: [:show, :edit, :update, :destroy]

  # GET /upload_pictures
  # GET /upload_pictures.json
  def index
    @upload_pictures = UploadPicture.order('start_date desc')
  end

  # GET /upload_pictures/1
  # GET /upload_pictures/1.json
  def show
  end

  # GET /upload_pictures/new
  def new
    @upload_picture = UploadPicture.new
  end

  # GET /upload_pictures/1/edit
  def edit
  end

  # POST /upload_pictures
  # POST /upload_pictures.json
  def create
    @upload_picture = UploadPicture.new(upload_picture_params)

    respond_to do |format|
      if @upload_picture.save
        format.html { redirect_to @upload_picture, notice: 'Upload picture was successfully created.' }
        format.json { render :show, status: :created, location: @upload_picture }
      else
        format.html { render :new }
        format.json { render json: @upload_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upload_pictures/1
  # PATCH/PUT /upload_pictures/1.json
  def update
    respond_to do |format|
      if @upload_picture.update(upload_picture_params)
        format.html { redirect_to @upload_picture, notice: 'Upload picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload_picture }
      else
        format.html { render :edit }
        format.json { render json: @upload_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upload_pictures/1
  # DELETE /upload_pictures/1.json
  def destroy
    @upload_picture.destroy
    respond_to do |format|
      format.html { redirect_to upload_pictures_url, notice: 'Upload picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def main
    @picture = UploadPicture.where([UploadPicture.arel_table[:start_date].not_eq(nil), UploadPicture.arel_table[:start_date].lt(Date.today)].reduce(&:and)).order('start_date desc').first
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload_picture
      @upload_picture = UploadPicture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_picture_params
      params.require(:upload_picture).permit(:image, :start_date, :description, :image_file_name, :image_content_type, :image_file_size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/upload_pictures_helper.rb
module UploadPicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UploadDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/upload_pictures/_form.html.erb
<%= form_for(@upload_picture) do |f| %>
  <% if @upload_picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload_picture.errors.count, "error") %> prohibited this upload_picture from being saved:</h2>

      <ul>
      <% @upload_picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/upload_pictures/edit.html.erb
<script>
  $( function() {
    $( "#upload_picture_start_date" ).datepicker({
    	dateFormat: "yy-mm-dd"
    });
  } );
</script>
<div class="container">
  <div class="upload-pic min-height">
    <div class="upload-title">Picture Preview</div>
    <div style="text-align: center;"><img src='<%= "/system/images/#{@upload_picture.image_file_name}"%>' /></div>
  </div>
	<div class="upload-files">
		<%= form_for(@upload_picture) do |f| %>
			Start Date: <%= f.text_field :start_date, :readonly => 'readonly' %>&nbsp;&nbsp;
			Description: <%= f.text_field :description %>
			<span style='float: right;'>
			  <%= f.submit 'Save' %>  |
			  <%= link_to 'Back', root_url %>
			</span>
		<% end %>
  </div>
</div>

app/views/upload_pictures/index.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>
	<div class="upload-files">
		<%= link_to 'Upload Picture', new_upload_picture_path %>
		<span style='float: right;'><%= link_to 'Back', root_url %><span>
	</div>
	<div style="padding: 25px;" id='pictures_div'>
		<table>
  		<thead>
    		<tr>
      		<th>Picture</th>
      		<th>Start Date</th>
      		<th>Description</th>
      		<th>Actions</th>
    		</tr>
  		</thead>
  		<tbody>
    		<% @upload_pictures.each do |upload_picture| %>
					<tr is="picture-tr" src='<%= "/system/images/#{upload_picture.image_file_name}"%>' start_date="<%= upload_picture.start_date %>" description="<%= upload_picture.description %>" show_url="<%= upload_picture_path(upload_picture) %>" edit_url="<%= edit_upload_picture_path(upload_picture) %>" destroy_url="<%= upload_picture_path(upload_picture) %>"></tr>
    		<% end %>
  		</tbody>
		</table>
	</div>
</div>
<script type="text/javascript">
  Vue.component('picture-tr', {
    props: ['src', 'start_date', 'description', 'show_url', 'edit_url', 'destroy_url'],
    template: `
			<tr>
				<td><div style="text-align: center;" class="list-pic"><img :src="src" /></div></td>
    		<td>{{ start_date }}</td>
				<td>{{ description }}</td>
    		<td>
					<a :href="show_url">Show</a>
					<a :href="edit_url">Edit</a>
					<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" :href="destroy_url">Destroy</a>
    			</td>
			</tr>
		`
  });
  new Vue({el: "#pictures_div"});
</script>

app/views/upload_pictures/main.html.erb
<div class="container">
  <div class="upload-pic min-height">
		<div class="upload-title">Today's Picture</div>
    <div class="upload-message">
      <% unless @picture.blank? %><span style="font-size:90%;"><%= @picture.description %></span><% end %>
      <span style="float:right;width:120px;text-align:right;"><a href="<%= new_upload_picture_path %>">Submit Your Picture</a></span>
		</div>
    <div style="text-align: center;"><% unless @picture.blank? %><img src='<%= "/system/images/#{@picture.image_file_name}"%>' /><% end %></div>
  </div>
	<div class="upload-files">
		<span style='float: center;'>
		  <%= link_to 'Manage Pictures', upload_pictures_path %>
		</span>
  </div>
</div>

app/views/upload_pictures/new.html.erb
<script>
  $( function() {
    $( "#upload_picture_start_date" ).datepicker({
    	dateFormat: "yy-mm-dd"
    });
  } );
</script>
<%= form_for(@upload_picture,:html => { :multipart => true }) do |f| %>
	<% message = 'Picture should be in jpg / png / gif format' %>
	<% error_message = '' %>
  <% @upload_picture.errors.full_messages.each do |msg|
  	error_message += "#{msg}<br />"
  end %>
  <div class="container">
    <div class="upload-pic min-height">
      <div class="upload-title">Picture Preview</div>
      <div class="message-span"><span><%=raw error_message.blank? ? message : error_message %></span></div>
    </div>
		<div class="upload-files">
			File: <%= f.file_field :image %>
			Start Date: <%= f.text_field :start_date, :readonly => 'readonly' %>&nbsp;&nbsp;
			Description: <%= f.text_field :description %>
			<span style='float: right; padding: 10px;'>
			  <%= f.submit 'Upload' %> |
			  <%= link_to 'Back', root_url %>
			<span>
    </div>
  </div>
<% end %>

app/views/upload_pictures/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="upload-pic min-height">
    <div class="upload-title">Picture Preview</div>
    <div style="text-align: center;"><img src='<%= "/system/images/#{@upload_picture.image_file_name}"%>' /></div>
  </div>
	<div class="upload-files">
		<%= "Start Date: #{@upload_picture.start_date}" unless @upload_picture.start_date.blank? %>&nbsp;&nbsp;
		<%= "Description: #{@upload_picture.description}" unless @upload_picture.description.blank? %>
		<span style='float: right;'>
		  <%= link_to 'Edit', edit_upload_picture_path(@upload_picture) %> |
		  <%= link_to 'Back', root_url %>
		</span>
  </div>
</div>